insert into areroporto (nome, nazione, citta, numeropiste) values ('NDJ', 'Czech Republic', 'Krmelín', 2);
insert into areroporto (nome, nazione, citta, numeropiste) values ('FOM', 'Guatemala', 'Quesada', 3);
insert into areroporto (nome, nazione, citta, numeropiste) values ('YBP', 'Indonesia', 'Mujur', 2);
insert into areroporto (nome, nazione, citta, numeropiste) values ('UYN', 'Indonesia', 'Bantardawa', 4);
insert into areroporto (nome, nazione, citta, numeropiste) values ('RAG', 'Mauritania', 'Tékane', 3);
insert into areroporto (nome, nazione, citta, numeropiste) values ('CEA', 'Indonesia', 'Ambat', 3);
insert into areroporto (nome, nazione, citta, numeropiste) values ('BVS', 'China', 'Jiefang', 1);
insert into areroporto (nome, nazione, citta, numeropiste) values ('DOV', 'Uganda', 'Namasuba', 2);
insert into areroporto (nome, nazione, citta, numeropiste) values ('EMY', 'China', 'Guyi', 1);
insert into areroporto (nome, nazione, citta, numeropiste) values ('DDP', 'Indonesia', 'Bantu', 4);
insert into areroporto (nome, nazione, citta, numeropiste) values ('HIL', 'China', 'Zhuoshui', 4);
insert into areroporto (nome, nazione, citta, numeropiste) values ('LPY', 'Ukraine', 'Lanchyn', 3);
insert into areroporto (nome, nazione, citta, numeropiste) values ('HTV', 'Colombia', 'El Copey', 2);
insert into areroporto (nome, nazione, citta, numeropiste) values ('LUY', 'United States', 'Austin', 1);
insert into areroporto (nome, nazione, citta, numeropiste) values ('CMQ', 'Ukraine', 'Poroshkovo', 2);
insert into areroporto (nome, nazione, citta, numeropiste) values ('JSY', 'China', 'Maoshan', 1);
insert into areroporto (nome, nazione, citta, numeropiste) values ('ASL', 'Brazil', 'Rio de Janeiro', 3);
insert into areroporto (nome, nazione, citta, numeropiste) values ('LVM', 'Argentina', 'Jacinto Arauz', 3);
insert into areroporto (nome, nazione, citta, numeropiste) values ('NMN', 'Poland', 'Stara Kornica', 3);
insert into areroporto (nome, nazione, citta, numeropiste) values ('RCK', 'China', 'Dongjiao', 1);
insert into areroporto (nome, nazione, citta, numeropiste) values ('AES', 'South Africa', 'Worcester', 1);
insert into areroporto (nome, nazione, citta, numeropiste) values ('SKJ', 'Indonesia', 'Jambean', 3);
insert into areroporto (nome, nazione, citta, numeropiste) values ('DLU', 'Philippines', 'Idtig', 1);
insert into areroporto (nome, nazione, citta, numeropiste) values ('UUA', 'Indonesia', 'Pantai', 4);
insert into areroporto (nome, nazione, citta, numeropiste) values ('TEB', 'Indonesia', 'Baratleke', 4);
insert into areroporto (nome, nazione, citta, numeropiste) values ('SBT', 'Portugal', 'Seara', 1);
insert into areroporto (nome, nazione, citta, numeropiste) values ('TQR', 'Indonesia', 'Kaduseeng', 1);
insert into areroporto (nome, nazione, citta, numeropiste) values ('UCT', 'Indonesia', 'Poli', 2);
insert into areroporto (nome, nazione, citta, numeropiste) values ('PCC', 'China', 'Niaohe', 4);
insert into areroporto (nome, nazione, citta, numeropiste) values ('CBU', 'Kosovo', 'Obiliq', 1);
insert into areroporto (nome, nazione, citta, numeropiste) values ('BOY', 'France', 'Orléans', 1);
insert into areroporto (nome, nazione, citta, numeropiste) values ('TLA', 'Philippines', 'Canaman', 2);
insert into areroporto (nome, nazione, citta, numeropiste) values ('ADH', 'Indonesia', 'Oeleon', 1);
insert into areroporto (nome, nazione, citta, numeropiste) values ('SSD', 'France', 'Puteaux', 1);
insert into areroporto (nome, nazione, citta, numeropiste) values ('FSZ', 'Greece', 'Kímolos', 3);
insert into areroporto (nome, nazione, citta, numeropiste) values ('DSI', 'Indonesia', 'Garawati', 3);
insert into areroporto (nome, nazione, citta, numeropiste) values ('DOP', 'Vietnam', 'Vũ Quang', 2);
insert into areroporto (nome, nazione, citta, numeropiste) values ('ELK', 'France', 'Vernon', 1);
insert into areroporto (nome, nazione, citta, numeropiste) values ('QPH', 'Russia', 'Devitsa', 4);
insert into areroporto (nome, nazione, citta, numeropiste) values ('ORK', 'Cameroon', 'Bafoussam', 2);
insert into areroporto (nome, nazione, citta, numeropiste) values ('CKS', 'China', 'Jinping', 4);
insert into areroporto (nome, nazione, citta, numeropiste) values ('GAQ', 'China', 'Hongshanyao', 3);
insert into areroporto (nome, nazione, citta, numeropiste) values ('HLC', 'China', 'Huicheng', 3);
insert into areroporto (nome, nazione, citta, numeropiste) values ('SKB', 'Russia', 'Sivaki', 1);
insert into areroporto (nome, nazione, citta, numeropiste) values ('LET', 'Canada', 'Gibbons', 2);
insert into areroporto (nome, nazione, citta, numeropiste) values ('BXS', 'China', 'Hongwei', 1);
insert into areroporto (nome, nazione, citta, numeropiste) values ('FFO', 'Brazil', 'Porto União', 1);
insert into areroporto (nome, nazione, citta, numeropiste) values ('GRY', 'Cambodia', 'Kampong Chhnang', 2);
insert into areroporto (nome, nazione, citta, numeropiste) values ('CNA', 'Poland', 'Pamiątkowo', 4);
insert into areroporto (nome, nazione, citta, numeropiste) values ('RUP', 'Panama', 'Pedregal', 2);
insert into areroporto (nome, nazione, citta, numeropiste) values ('HUQ', 'China', 'Xiaomei', 1);
insert into areroporto (nome, nazione, citta, numeropiste) values ('EOH', 'Colombia', 'La Jagua de Ibirico', 4);
insert into areroporto (nome, nazione, citta, numeropiste) values ('RLT', 'Indonesia', 'Sindangkopo', 4);
insert into areroporto (nome, nazione, citta, numeropiste) values ('CMB', 'China', 'Shuangqiao', 1);
insert into areroporto (nome, nazione, citta, numeropiste) values ('PPZ', 'Russia', 'Makarov', 1);
insert into areroporto (nome, nazione, citta, numeropiste) values ('BOQ', 'China', 'Labrang', 2);
insert into areroporto (nome, nazione, citta, numeropiste) values ('AHT', 'Indonesia', 'Citeguh', 4);
insert into areroporto (nome, nazione, citta, numeropiste) values ('YLV', 'United States', 'Reno', 2);
insert into areroporto (nome, nazione, citta, numeropiste) values ('LKB', 'Indonesia', 'Sobo', 4);
insert into areroporto (nome, nazione, citta, numeropiste) values ('OVD', 'Indonesia', 'Cihurip Satu', 4);
insert into areroporto (nome, nazione, citta, numeropiste) values ('AUA', 'Germany', 'Wetzlar', 4);
insert into areroporto (nome, nazione, citta, numeropiste) values ('TMB', 'Indonesia', 'Nangerang', 3);
insert into areroporto (nome, nazione, citta, numeropiste) values ('AFZ', 'Indonesia', 'Jadho', 1);
insert into areroporto (nome, nazione, citta, numeropiste) values ('DAG', 'China', 'Yanmen', 3);
insert into areroporto (nome, nazione, citta, numeropiste) values ('YWQ', 'Dominican Republic', 'Gonzalo', 2);
insert into areroporto (nome, nazione, citta, numeropiste) values ('ITK', 'China', 'Jinchuan', 4);
insert into areroporto (nome, nazione, citta, numeropiste) values ('BHX', 'China', 'Oymak', 1);
insert into areroporto (nome, nazione, citta, numeropiste) values ('YBH', 'China', 'Qiqian', 1);
insert into areroporto (nome, nazione, citta, numeropiste) values ('KHH', 'France', 'Reims', 1);
insert into areroporto (nome, nazione, citta, numeropiste) values ('NDL', 'Somalia', 'Jawhar', 2);
insert into areroporto (nome, nazione, citta, numeropiste) values ('AAH', 'Indonesia', 'Leran', 1);
insert into areroporto (nome, nazione, citta, numeropiste) values ('ORK', 'Venezuela', 'San Francisco', 4);
insert into areroporto (nome, nazione, citta, numeropiste) values ('BWM', 'Dominican Republic', 'Salvaleón de Higüey', 2);
insert into areroporto (nome, nazione, citta, numeropiste) values ('LSY', 'China', 'Didian', 1);
insert into areroporto (nome, nazione, citta, numeropiste) values ('JYR', 'Poland', 'Wodzisław Śląski', 3);
insert into areroporto (nome, nazione, citta, numeropiste) values ('BPD', 'Philippines', 'Arteche', 4);
insert into areroporto (nome, nazione, citta, numeropiste) values ('LFR', 'Canada', 'Bonnyville', 3);
insert into areroporto (nome, nazione, citta, numeropiste) values ('SZP', 'China', 'Liucun', 2);
insert into areroporto (nome, nazione, citta, numeropiste) values ('LPB', 'China', 'Chashan', 3);
insert into areroporto (nome, nazione, citta, numeropiste) values ('YAG', 'Finland', 'Siikainen', 3);
insert into areroporto (nome, nazione, citta, numeropiste) values ('TIN', 'Indonesia', 'Ciloa', 2);
insert into areroporto (nome, nazione, citta, numeropiste) values ('TPK', 'China', 'Jincun', 4);
insert into areroporto (nome, nazione, citta, numeropiste) values ('CPV', 'Belarus', 'Karelichy', 1);
insert into areroporto (nome, nazione, citta, numeropiste) values ('ERE', 'France', 'Saint-Rémy-de-Provence', 3);
insert into areroporto (nome, nazione, citta, numeropiste) values ('RKP', 'Indonesia', 'Kakaek', 4);
insert into areroporto (nome, nazione, citta, numeropiste) values ('BXI', 'United States', 'Fort Lauderdale', 1);
insert into areroporto (nome, nazione, citta, numeropiste) values ('KVG', 'Ecuador', 'Atuntaqui', 1);
insert into areroporto (nome, nazione, citta, numeropiste) values ('XLU', 'Poland', 'Ochla', 4);
insert into areroporto (nome, nazione, citta, numeropiste) values ('PTF', 'Afghanistan', 'Ḩājī Khēl', 2);
insert into areroporto (nome, nazione, citta, numeropiste) values ('OKI', 'Bulgaria', 'Svilengrad', 3);
insert into areroporto (nome, nazione, citta, numeropiste) values ('KBV', 'Ivory Coast', 'Sinfra', 3);
insert into areroporto (nome, nazione, citta, numeropiste) values ('OKS', 'Indonesia', 'Naifalo', 4);
insert into areroporto (nome, nazione, citta, numeropiste) values ('HKG', 'United States', 'Evansville', 3);
insert into areroporto (nome, nazione, citta, numeropiste) values ('PTF', 'Syria', 'Duraykīsh', 2);
insert into areroporto (nome, nazione, citta, numeropiste) values ('JNI', 'Dominican Republic', 'Tamboril', 3);
insert into areroporto (nome, nazione, citta, numeropiste) values ('EOH', 'Ireland', 'Tower', 4);
insert into areroporto (nome, nazione, citta, numeropiste) values ('DUA', 'Serbia', 'Belo Blato', 1);
insert into areroporto (nome, nazione, citta, numeropiste) values ('LBU', 'Macedonia', 'Oslomej', 1);
insert into areroporto (nome, nazione, citta, numeropiste) values ('HOT', 'Macedonia', 'Јегуновце', 4);
insert into areroporto (nome, nazione, citta, numeropiste) values ('DCR', 'China', 'Hongyuan', 2);
insert into areroporto (nome, nazione, citta, numeropiste) values ('FEB', 'Ukraine', 'Nelipyno', 3);
insert into areroporto (nome, nazione, citta, numeropiste) values ('ISK', 'Poland', 'Świebodzice', 1);
insert into areroporto (nome, nazione, citta, numeropiste) values ('YNZ', 'Brazil', 'Ceará Mirim', 3);
insert into areroporto (nome, nazione, citta, numeropiste) values ('ZAL', 'Bulgaria', 'Yambol', 2);
insert into areroporto (nome, nazione, citta, numeropiste) values ('FNR', 'Indonesia', 'Ciomas', 4);
insert into areroporto (nome, nazione, citta, numeropiste) values ('PVU', 'Peru', 'Bellavista', 4);
insert into areroporto (nome, nazione, citta, numeropiste) values ('FAI', 'Indonesia', 'Tiro', 3);
insert into areroporto (nome, nazione, citta, numeropiste) values ('HNH', 'Russia', 'Tselinnoye', 1);
insert into areroporto (nome, nazione, citta, numeropiste) values ('CNX', 'United States', 'Washington', 4);
insert into areroporto (nome, nazione, citta, numeropiste) values ('HVB', 'China', 'Longshi', 1);
insert into areroporto (nome, nazione, citta, numeropiste) values ('XAU', 'China', 'Hehe', 4);
insert into areroporto (nome, nazione, citta, numeropiste) values ('QGS', 'South Korea', 'Songgang-dong', 4);
insert into areroporto (nome, nazione, citta, numeropiste) values ('BDT', 'Panama', 'Potrerillos Arriba', 3);
insert into areroporto (nome, nazione, citta, numeropiste) values ('NEW', 'China', 'Shangjie', 2);
insert into areroporto (nome, nazione, citta, numeropiste) values ('MEV', 'Bangladesh', 'Pālang', 1);
insert into areroporto (nome, nazione, citta, numeropiste) values ('EUG', 'Indonesia', 'Cikiruh Wetan', 1);
insert into areroporto (nome, nazione, citta, numeropiste) values ('HRE', 'Argentina', 'Colonia Aurora', 3);
insert into areroporto (nome, nazione, citta, numeropiste) values ('BHX', 'Venezuela', 'El Corozo', 3);
insert into areroporto (nome, nazione, citta, numeropiste) values ('ISK', 'China', 'Sanhui', 4);
insert into areroporto (nome, nazione, citta, numeropiste) values ('TBQ', 'China', 'Hecheng', 2);
insert into areroporto (nome, nazione, citta, numeropiste) values ('SOW', 'Canada', 'Sylvan Lake', 2);
insert into areroporto (nome, nazione, citta, numeropiste) values ('TWB', 'Japan', 'Ōmuta', 2);
insert into areroporto (nome, nazione, citta, numeropiste) values ('TZR', 'France', 'Marne-la-Vallée', 3);
insert into areroporto (nome, nazione, citta, numeropiste) values ('LPO', 'Russia', 'Fryanovo', 4);
insert into areroporto (nome, nazione, citta, numeropiste) values ('HOY', 'Russia', 'Ekimchan', 2);
insert into areroporto (nome, nazione, citta, numeropiste) values ('YBV', 'Portugal', 'Sever do Vouga', 4);
insert into areroporto (nome, nazione, citta, numeropiste) values ('GFR', 'Malaysia', 'Shah Alam', 4);
insert into areroporto (nome, nazione, citta, numeropiste) values ('TBO', 'Zambia', 'Nakambala', 2);
insert into areroporto (nome, nazione, citta, numeropiste) values ('WGB', 'Thailand', 'Sawang Daen Din', 2);
insert into areroporto (nome, nazione, citta, numeropiste) values ('GKH', 'Brazil', 'Caraguatatuba', 4);
insert into areroporto (nome, nazione, citta, numeropiste) values ('YNG', 'Japan', 'Sasebo', 1);
insert into areroporto (nome, nazione, citta, numeropiste) values ('LIP', 'Canada', 'Oxbow', 4);
insert into areroporto (nome, nazione, citta, numeropiste) values ('IIA', 'France', 'Évry', 4);
insert into areroporto (nome, nazione, citta, numeropiste) values ('TAM', 'Brazil', 'Rio Bonito', 4);
insert into areroporto (nome, nazione, citta, numeropiste) values ('ATO', 'Poland', 'Słupsk', 2);
insert into areroporto (nome, nazione, citta, numeropiste) values ('NAR', 'Slovenia', 'Tržič', 1);
insert into areroporto (nome, nazione, citta, numeropiste) values ('KZR', 'Israel', 'Bené Beraq', 2);
insert into areroporto (nome, nazione, citta, numeropiste) values ('BTC', 'Italy', 'Verona', 1);
insert into areroporto (nome, nazione, citta, numeropiste) values ('VPY', 'Philippines', 'Granada', 1);
insert into areroporto (nome, nazione, citta, numeropiste) values ('MYT', 'China', 'Yujiawu', 3);
insert into areroporto (nome, nazione, citta, numeropiste) values ('HFE', 'Russia', 'Ol’gino', 2);
insert into areroporto (nome, nazione, citta, numeropiste) values ('UKT', 'South Africa', 'Knysna', 4);
insert into areroporto (nome, nazione, citta, numeropiste) values ('GRT', 'Tajikistan', 'Isfara', 1);
insert into areroporto (nome, nazione, citta, numeropiste) values ('RCY', 'Sweden', 'Nykvarn', 2);
insert into areroporto (nome, nazione, citta, numeropiste) values ('YXP', 'Indonesia', 'Wadung', 4);
insert into areroporto (nome, nazione, citta, numeropiste) values ('PCJ', 'Tanzania', 'Magugu', 2);
insert into areroporto (nome, nazione, citta, numeropiste) values ('FAJ', 'Portugal', 'Fortios', 3);
insert into areroporto (nome, nazione, citta, numeropiste) values ('LNS', 'Russia', 'Polyarnyye Zori', 4);
insert into areroporto (nome, nazione, citta, numeropiste) values ('OXY', 'Nigeria', 'Tegina', 4);
insert into areroporto (nome, nazione, citta, numeropiste) values ('TBG', 'Egypt', 'Al Manshāh', 2);
insert into areroporto (nome, nazione, citta, numeropiste) values ('GLR', 'Albania', 'Pirg', 4);
insert into areroporto (nome, nazione, citta, numeropiste) values ('TKI', 'Colombia', 'Remolino', 4);
insert into areroporto (nome, nazione, citta, numeropiste) values ('YDP', 'China', 'Hulan', 4);
insert into areroporto (nome, nazione, citta, numeropiste) values ('AFT', 'China', 'Zhanjia', 4);
insert into areroporto (nome, nazione, citta, numeropiste) values ('DTU', 'Albania', 'Elbasan', 1);
insert into areroporto (nome, nazione, citta, numeropiste) values ('KNJ', 'Russia', 'Novokuz’minki', 4);
insert into areroporto (nome, nazione, citta, numeropiste) values ('TVA', 'Honduras', 'Mangulile', 3);
insert into areroporto (nome, nazione, citta, numeropiste) values ('GYG', 'Moldova', 'Biruinţa', 2);
insert into areroporto (nome, nazione, citta, numeropiste) values ('KIP', 'Sweden', 'Borås', 1);
insert into areroporto (nome, nazione, citta, numeropiste) values ('MAU', 'Indonesia', 'Gisiliba', 4);
insert into areroporto (nome, nazione, citta, numeropiste) values ('MRH', 'Brazil', 'Iracemápolis', 1);
insert into areroporto (nome, nazione, citta, numeropiste) values ('ZRI', 'Canada', 'Grand Bank', 4);
insert into areroporto (nome, nazione, citta, numeropiste) values ('BUM', 'China', 'Lücheng', 4);
insert into areroporto (nome, nazione, citta, numeropiste) values ('0', 'Indonesia', 'Condong', 3);
insert into areroporto (nome, nazione, citta, numeropiste) values ('SAN', 'Czech Republic', 'Albrechtice', 2);
insert into areroporto (nome, nazione, citta, numeropiste) values ('HTZ', 'Sweden', 'Oxelösund', 3);
insert into areroporto (nome, nazione, citta, numeropiste) values ('PIT', 'Peru', 'Cuchumbaya', 3);
insert into areroporto (nome, nazione, citta, numeropiste) values ('FIK', 'Nigeria', 'Rabah', 4);
insert into areroporto (nome, nazione, citta, numeropiste) values ('MCF', 'Philippines', 'Lanipao', 2);
insert into areroporto (nome, nazione, citta, numeropiste) values ('VKT', 'France', 'Saint-Jean-de-Monts', 3);
insert into areroporto (nome, nazione, citta, numeropiste) values ('RHT', 'China', 'Wanshi', 4);
insert into areroporto (nome, nazione, citta, numeropiste) values ('KSX', 'Finland', 'Liminka', 3);
insert into areroporto (nome, nazione, citta, numeropiste) values ('TNC', 'Ivory Coast', 'Ferkessédougou', 4);
insert into areroporto (nome, nazione, citta, numeropiste) values ('SVJ', 'China', 'Taihe', 2);
insert into areroporto (nome, nazione, citta, numeropiste) values ('TQD', 'Canada', 'La Tuque', 2);
insert into areroporto (nome, nazione, citta, numeropiste) values ('HSB', 'Portugal', 'Quinta dos Frades', 2);
insert into areroporto (nome, nazione, citta, numeropiste) values ('XYR', 'China', 'Benhao', 2);
insert into areroporto (nome, nazione, citta, numeropiste) values ('GOL', 'Greece', 'Oinoússes', 4);
insert into areroporto (nome, nazione, citta, numeropiste) values ('LWI', 'Portugal', 'Paranho', 4);
insert into areroporto (nome, nazione, citta, numeropiste) values ('EVD', 'Philippines', 'Saguday', 4);
insert into areroporto (nome, nazione, citta, numeropiste) values ('LTL', 'China', 'Sihe', 2);
insert into areroporto (nome, nazione, citta, numeropiste) values ('OKH', 'Hungary', 'Pápa', 1);
insert into areroporto (nome, nazione, citta, numeropiste) values ('BCN', 'Sweden', 'Örebro', 1);
insert into areroporto (nome, nazione, citta, numeropiste) values ('PTV', 'Serbia', 'Bajina Bašta', 1);
insert into areroporto (nome, nazione, citta, numeropiste) values ('TOT', 'China', 'Qian’an', 3);
insert into areroporto (nome, nazione, citta, numeropiste) values ('BWM', 'Ivory Coast', 'Duekoué', 3);
insert into areroporto (nome, nazione, citta, numeropiste) values ('HPV', 'Bosnia and Herzegovina', 'Gornje Živinice', 2);
insert into areroporto (nome, nazione, citta, numeropiste) values ('CUD', 'China', 'Dacun', 2);
insert into areroporto (nome, nazione, citta, numeropiste) values ('PME', 'Brazil', 'Panambi', 4);
insert into areroporto (nome, nazione, citta, numeropiste) values ('ONG', 'Brazil', 'Coxim', 2);
insert into areroporto (nome, nazione, citta, numeropiste) values ('SVK', 'Thailand', 'Roi Et', 1);
insert into areroporto (nome, nazione, citta, numeropiste) values ('ASE', 'Sweden', 'Borås', 1);
insert into areroporto (nome, nazione, citta, numeropiste) values ('XPK', 'Canada', 'Pont-Rouge', 1);
insert into areroporto (nome, nazione, citta, numeropiste) values ('ENF', 'South Africa', 'Ixopo', 2);
insert into areroporto (nome, nazione, citta, numeropiste) values ('SNW', 'China', 'Liudu', 2);
insert into areroporto (nome, nazione, citta, numeropiste) values ('ULN', 'Indonesia', 'Trucuk', 4);
insert into areroporto (nome, nazione, citta, numeropiste) values ('OVS', 'Russia', 'Belomorsk', 2);
insert into areroporto (nome, nazione, citta, numeropiste) values ('DWR', 'Serbia', 'Palilula', 1);
insert into areroporto (nome, nazione, citta, numeropiste) values ('CKN', 'Indonesia', 'Kuma', 4);
insert into areroporto (nome, nazione, citta, numeropiste) values ('MFP', 'Brazil', 'São Caetano do Sul', 1);
